taskkill /F /IM "Adobe Desktop Service.exe"
taskkill /F /IM "CCLibrary.exe"
taskkill /F /IM "CCXProcess.exe"
taskkill /F /IM "acrotray.exe"
taskkill /F /IM "AdobeIPCBroker.exe"
taskkill /F /IM "CoreSync.exe"
taskkill /F /IM "Creative Cloud Helper.exe"
taskkill /F /IM "AdobeNotificationClient.exe"
taskkill /F /IM "AcrobatNotificationClient.exe"
